Feature/nanoflow
FlockOfBirds/GeolocationForPhoneGap pull request #1
Opened 2018-05-15 12:19 UTC by jseremba

- Update icon
- Add nanoflow support

2018-05-16 13:07 UTC, McDoyen requested changes

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "description": "",
Add the discription

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "license": "",
Add licence

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "author": "",
Remove author

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "license": "",
Copyright is missing

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "private": true,
Remove "private": true, its a public widget

2018-05-16 13:07 UTC, McDoyen commented on package.json
> +  "private": true,
URLs are missing ie. repository and issues

2018-05-16 13:07 UTC, McDoyen commented on src/GeoLocationForPhoneGap/GeoLocationForPhoneGap.xml
> -        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABx0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzIENTNui8sowAAAWpcHJWV3ic7Vvbcew2DKX46CMtZNxIWshHnN/bjpu
Remove line

2018-05-17 07:48 UTC, jseremba commented on package.json
> +  "description": "",
Done

2018-05-17 07:49 UTC, jseremba commented on package.json
> +  "license": "",
Done

2018-05-17 07:49 UTC, jseremba commented on package.json
> +  "author": "",
Done

2018-05-17 07:49 UTC, jseremba commented on package.json
> +  "license": "",
Done

2018-05-17 07:49 UTC, jseremba commented on package.json
> +  "private": true,
Done

2018-05-17 07:49 UTC, jseremba commented on package.json
> +  "private": true,
Done

2018-05-30 12:14 UTC, merged